baseURL: "https://www.angelortiz.io"
languageCode: "en-us"
title: "Angel Ortiz | Software Engineer"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
#Dropdown menu
# - identifier: dropdown
#   title: Example dropdown menu
#   name: Dropdown
#   weight: 3
# - identifier: dropdown1
#   title: example dropdown 1
#   name: example 1
#   url: /#
#   parent: dropdown
#   weight: 1
# - identifier: dropdown2
#   title: example dropdown 2
#   name: example 2
#   url: /#
#   parent: dropdown
#   weight: 2

params:
  title: "Angel Ortiz"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor:
    secondaryTextColor:
    backgroundColor:
    secondaryBackgroundColor:
    primaryColor:
    secondaryColor:

    darkmode:
      textColor:
      secondaryTextColor:
      backgroundColor:
      secondaryBackgroundColor:
      primaryColor:
      secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo.svg" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Angel Ortiz" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello there! My name is"
    title: "Angel."
    subtitle: "your friendly neighborhood web app developer. 🚀"
    content: |
      I'm a web enthusiast constantly exploring cutting-edge technologies to ensure your websites look stunning, offer seamless experiences, and work like a charm.

      Why Choose Me:

        ✨ Expertise in modern web technologies.

        ✨ A commitment to exceptional design and functionality.

        ✨ Your vision, my code - we make magic happen!

      Let's create together!

    image: /images/greeting.png
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/angelortiz-io
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/angelortiz-io/
        - icon: fab fa-twitter
          url: https://twitter.com/aandresortiz
      #customIcons:

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/coder.png"
    content: |
      I bring over a decade of seasoned experience as a Senior Software Engineer specializing in web development. My core strengths revolve around Python programming and effective team leadership, enabling me to consistently guide teams to on-budget, timely project deliveries. My expertise encompasses various Python frameworks like Django, FastAPI, and Flask, where I excel in the implementation of Rest APIs and microservices.

      Additionally, I possess practical hands-on familiarity with AWS services, including EC2, S3, Lambda, API Gateway, Route 53, DynamoDB, and Data Migration Services. My skill set extends to encompass RabbitMQ, Snowflake, PostgreSQL, and Github.

      Throughout my career, I've upheld a track record of consistently delivering projects characterized by high quality and scalability. My ability to quickly adapt and a collaborative team-oriented approach has been key to my success. I remain dedicated to staying abreast of the latest software development trends.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Django"
        - "Flask"
        - "FastAPI"
        - "SQL"
        - "Docker"
        - "Numpy"
        - "Pandas"
        - "AWS"
        - "JavaScript"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Engineer at Johnson & Johnson"
        company: "Globant"
        companyUrl: "https://www.globant.com"
        date: "Jul 2023 - present"
        content: |
          Experienced Data Engineer at Johnson & Johnson with a proven track record of leveraging Python, AWS, PostgreSQL, and data pipelines to drive data excellence.

          Responsibilities:

          - Designed and developed robust data pipelines for ETL processes.
          - Managed PostgreSQL databases, optimizing query performance and data integrity.
          - Integrated data from diverse sources into a unified platform.
          - Implemented automation for data processing and manipulation with pandas.
          - Leveraged AWS services (S3, Glue, Lambda) for efficient data management.
          - Ensured data governance and compliance with security standards.
          - Established monitoring systems and conducted routine data maintenance.
          - Contributed to GDPR compliance through data masking and encryption.

          My role at Johnson & Johnson showcases my ability to drive data-driven decision-making and streamline data processes for organizational success. I'm passionate about leveraging technology to empower businesses through data.

      - job: "Python Developer"
        company: "Globant"
        companyUrl: "https://www.globant.com"
        date: "Jan 2023 - Jun 2023"
        content: |
          My main responsibility entailed conceptualizing, designing, and building a chat bot using the advanced AI language model, ChatGPT. This chat bot was specifically crafted to enable user interactions within the widely-used communication platform, Slack.

          The project resulted in several noteworthy accomplishments. These include the development of a fully operational proof of concept chat bot, serving as a compelling demonstration of ChatGPT's capabilities in automating interactions within a business setting. The incorporation of text-to-speech functionality notably boosted user engagement and accessibility. Additionally, the successful integration of the chat bot into Slack underscored its adaptability to pre-existing communication tools. Furthermore, favorable feedback received during user testing confirmed the bot's effectiveness in providing information and assistance. This experience illustrated my proficiency in harnessing AI technology to generate valuable solutions, highlighting the potential for similar AI-driven chat bots to enhance communication and operational efficiency in corporate environments.

      - job: "Lead Python Engineer at Smile Direct Club"
        company: "Globant"
        companyUrl: "https://www.globant.com"
        date: "Sep 2021 - Dec 2022"
        featuredLink:
          enable: true
          url: "https://smiledirectclub.com/"
        info:
          enable: true
          content: I worked as a Lead Python Engineer for more than one year in SmileDirectClub.
        content: |
          Lead Engineer for Smile Direct Club's flagship project, I was responsible for overseeing the development and implementation of REST APIs using Django and Python. I also utilized my expertise in Nuxt.js and Vue.js to develop the front-end user interface. Additionally, I managed a team of developers using Kanban methodology, ensuring that the project was delivered on time and within budget.

          Responsibilities:

          - Developed REST APIs and API development using Django and Python.
          - Created front-end user interface using Nuxt.js and Vue.js.
          - Utilized PostgreSQL for database management.
          - Managed a team of developers using scrum and kanban methodologies.
          - Designed and implemented features for the flagship project.
          - Conducted code reviews and provided technical guidance to team members.
          - Ensured code quality and adherence to best practices.
          - Collaborated with cross-functional teams to ensure project success.
          - Communicated project progress to stakeholders.
          - Delivered the project on time and within budget.

      - job: "Data Engineer at Paypal"
        company: "Thaloz"
        companyUrl: "https://www.thaloz.com"
        date: "May 2022 - Jan 2023"
        content: |
          I was responsible for designing and implementing data pipelines using a variety of technologies, including Amazon Elastic MapReduce (EMR), Docker, and Kubernetes. I also utilized my expertise in Snowflake, AWS Lambda, and AWS CDK to manage and migrate data across various sources. Additionally, I was responsible for writing complex SQL queries and Python scripts to transform and load data from disparate sources.

          Responsibilities:

          - Designed and implemented data pipelines using Amazon EMR, Docker, and Kubernetes.
          - Utilized Snowflake to manage and store data from various sources.
          - Developed AWS Lambda functions and used AWS CDK to manage infrastructure.
          - Conducted data migration across various sources, ensuring data integrity.
          - Wrote complex SQL queries and Python scripts to transform and load data.
          - Worked with cross-functional teams to ensure data quality and accuracy.
          - Utilized best practices for data engineering, ensuring scalability and maintainability.
          - Designed and implemented data models for new and existing data sources.
          - Monitored and optimized data pipelines for performance and efficiency.
          - Collaborated with data analysts and data scientists to develop insights from data.

      - job: "Software Engineer"
        company: "Talpor"
        companyUrl: "https://www.talpor.com"
        date: "Jan 2021 - Apr 2022"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://www.stanwinstonschool.com"
        content: |
          As a Full Stack Developer at Stan Winston School of Character Arts, I played a crucial role in the development and maintenance of the school's web platform. I utilized my expertise in Django, Django REST Framework, Celery, React.js, and Redux to deliver new features and improve the platform's user experience.

          Responsibilities:

          - Developed new API endpoints for the web platform, allowing for better data retrieval and management.
          - Improved the checkout process by developing new features and updating UI components, resulting in an increase in completed transactions.
          - Integrated Braintree into the backend, ensuring secure and reliable payment processing for users.
          - Developed new Celery tasks to enable asynchronous processing of tasks, improving overall performance and scalability of the platform.
          - Redesigned the landing page, resulting in a more modern and visually appealing frontend interface.
          - Maintained and optimized the platform's backend, including database management and server configuration.

      # - job: "Tech Lead & Software Engineer"
      #   company: "Burns the Agency"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Miica Tech"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      # - job: "Product Designer"
      #   company: "Wisboo"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Systems Engineering (truncated)"
        school:
          name: "Cesar Vallejo University"
          url: "https://www.ucv.edu.pe"
        date: "2007 - 2014"
        content: |-
          Extracurricular Activities
            - Dance. 
            - Scenic Arts.
            - Technical conference speaker.
      - title: ".Net Specialist"
        school:
          name: "Cesar Vallejo University"
          url: "https://www.ucv.edu.pe"
        date: "2011 - 2012"
        GPA: "4.1 out of 5.0"
        content: |-
          - ASP .Net
          - C# .Net
          - SQL Server
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "High School"
        school:
          name: "Alfredo Rebaza Acosta."
          url: "https://iealfredorebazaacosta.edu.pe/"
        date: "1999 - 2003"
        featuredLink:
          enable: true
          url: "https://iealfredorebazaacosta.edu.pe/"

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievment.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievment.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  # projects:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Hugo Profile
  #       content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile.png
  #       featured:
  #         name: Demo
  #         link: https://hugo-profile.netlify.app
  #       badges:
  #         - "Hugo"
  #         - "Bootstrap"
  #         - "Javascript"
  #       links:
  #         - icon: fa fa-envelope
  #           url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/hugo-profile
  #         - icon: fab fa-twitter
  #           url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  #     - title: Image Converter
  #       content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
  #       image: /images/projects/converter.jpg
  #       featured:
  #         name: Demo
  #         link: https://django-converter.herokuapp.com
  #       badges:
  #         - "Django"
  #         - "Bootstrap"
  #       links:
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/converter

  #     - title: Hugo Profile V2
  #       content: A clean and simple Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile2.jpg
  #       featured:
  #         name: Demo V2
  #         link: https://hugo-profile-2.netlify.app
  #       badges:
  #         - "Hugo"
  #         - "Bootstrap"
  #         - "Javascript"
  #       links:
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: aandresortiz@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/angelortiz-io
      linkedin: https://www.linkedin.com/in/angelortiz-io/
      twitter: https://twitter.com/aandresortiz
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
